#!/usr/bin/env node

/**
 * AICodeClaw MCP Server 测试脚本
 * 
 * 用途：验证所有 7 个 MCP 工具是否正常工作
 * 运行：node test.js
 */

import { spawn } from "child_process";
import { readFileSync, writeFileSync, unlinkSync, existsSync } from "fs";
import { join } from "path";

const TEST_DIR = process.cwd();
const SERVER_SCRIPT = join(TEST_DIR, "index.js");

// 测试文件路径
const TEST_FILE = join(TEST_DIR, "test-output.txt");
const HELLO_FILE = join(TEST_DIR, "hello.js");

// MCP JSON-RPC 请求
function makeRequest(id, method, params = {}) {
  return JSON.stringify({
    jsonrpc: "2.0",
    id,
    method,
    params
  });
}

// 运行测试
async function runTests() {
  console.log("🧪 AICodeClaw MCP Server 测试开始\n");
  console.log("=".repeat(60));

  const child = spawn("node", [SERVER_SCRIPT], {
    stdio: ["pipe", "pipe", "pipe"]
  });

  let outputBuffer = "";
  let requestId = 0;

  // 收集输出
  child.stdout.on("data", (data) => {
    outputBuffer += data.toString();
  });

  child.stderr.on("data", (data) => {
    console.log("📡 Server:", data.toString().trim());
  });

  // 发送请求
  function sendRequest(method, params) {
    requestId++;
    const request = makeRequest(requestId, method, params);
    child.stdin.write(request + "\n");
    return requestId;
  }

  // 等待响应
  function waitForResponse(id) {
    return new Promise((resolve) => {
      const check = setInterval(() => {
        const lines = outputBuffer.split("\n");
        for (const line of lines) {
          if (!line.trim()) continue;
          try {
            const response = JSON.parse(line);
            if (response.id === id) {
              clearInterval(check);
              resolve(response);
            }
          } catch (e) {
            // 忽略解析错误
          }
        }
      }, 100);
    });
  }

  try {
    // 测试 1: 初始化
    console.log("\n📋 测试 1: 初始化连接");
    const initId = sendRequest("initialize", {
      protocolVersion: "2024-11-05",
      capabilities: {},
      clientInfo: { name: "test-client", version: "1.0.0" }
    });
    const initResponse = await waitForResponse(initId);
    if (initResponse.result) {
      console.log("✅ 初始化成功");
      console.log(`   服务器: ${initResponse.result.serverInfo?.name || "unknown"}`);
      console.log(`   版本: ${initResponse.result.serverInfo?.version || "unknown"}`);
    } else {
      console.log("❌ 初始化失败");
    }

    // 测试 2: 获取工具列表
    console.log("\n📋 测试 2: 获取工具列表");
    const listId = sendRequest("tools/list", {});
    const listResponse = await waitForResponse(listId);
    if (listResponse.result?.tools) {
      console.log(`✅ 获取到 ${listResponse.result.tools.length} 个工具`);
      listResponse.result.tools.forEach((tool, i) => {
        console.log(`   ${i + 1}. ${tool.name} - ${tool.description}`);
      });
    } else {
      console.log("❌ 获取工具列表失败");
    }

    // 测试 3: 写入测试文件（Hello World 代码）
    console.log("\n📋 测试 3: 写入 Hello World 代码");
    const helloCode = `// Hello World - Generated by AICodeClaw MCP Server
console.log("Hello, World!");
console.log("AICodeClaw MCP Server 测试成功！");
`;
    const writeId = sendRequest("tools/call", {
      name: "aicodclaw_file_write",
      arguments: {
        path: HELLO_FILE,
        content: helloCode
      }
    });
    const writeResponse = await waitForResponse(writeId);
    if (writeResponse.result?.content?.[0]?.text?.includes("written")) {
      console.log("✅ 文件写入成功");
      console.log(`   路径: ${HELLO_FILE}`);
    } else {
      console.log("❌ 文件写入失败");
      console.log("   响应:", JSON.stringify(writeResponse.result));
    }

    // 测试 4: 读取文件验证
    console.log("\n📋 测试 4: 读取文件验证");
    const readId = sendRequest("tools/call", {
      name: "aicodclaw_file_read",
      arguments: { path: HELLO_FILE }
    });
    const readResponse = await waitForResponse(readId);
    if (readResponse.result?.content?.[0]?.text?.includes("Hello, World!")) {
      console.log("✅ 文件读取成功");
      console.log("   内容包含: Hello, World!");
    } else {
      console.log("❌ 文件读取失败");
    }

    // 测试 5: 执行 Shell 命令（运行 Hello World）
    console.log("\n📋 测试 5: 运行 Hello World 代码");
    const shellId = sendRequest("tools/call", {
      name: "aicodclaw_shell",
      arguments: {
        command: `node "${HELLO_FILE}"`,
        cwd: TEST_DIR
      }
    });
    const shellResponse = await waitForResponse(shellId);
    const shellOutput = shellResponse.result?.content?.[0]?.text || "";
    if (shellOutput.includes("Hello, World!")) {
      console.log("✅ Shell 命令执行成功");
      console.log("   输出:");
      shellOutput.split("\n").forEach(line => {
        if (line.trim()) console.log(`     ${line.trim()}`);
      });
    } else {
      console.log("❌ Shell 命令执行失败");
      console.log("   输出:", shellOutput);
    }

    // 测试 6: 代码搜索
    console.log("\n📋 测试 6: 搜索代码");
    const searchId = sendRequest("tools/call", {
      name: "aicodclaw_search",
      arguments: {
        path: TEST_DIR,
        pattern: "Hello, World!"
      }
    });
    const searchResponse = await waitForResponse(searchId);
    const searchOutput = searchResponse.result?.content?.[0]?.text || "";
    if (searchOutput.includes("Hello, World!") || searchOutput.includes("No matches")) {
      console.log("✅ 代码搜索正常");
      console.log(`   结果: ${searchOutput.split("\n")[0]}`);
    } else {
      console.log("❌ 代码搜索异常");
    }

    // 清理测试文件
    console.log("\n🧹 清理测试文件");
    if (existsSync(HELLO_FILE)) {
      unlinkSync(HELLO_FILE);
      console.log("✅ 已删除 hello.js");
    }
    if (existsSync(TEST_FILE)) {
      unlinkSync(TEST_FILE);
      console.log("✅ 已删除 test-output.txt");
    }

  } catch (error) {
    console.error("\n❌ 测试出错:", error.message);
  } finally {
    // 关闭服务器
    child.stdin.end();
    child.kill();

    console.log("\n" + "=".repeat(60));
    console.log("🎉 测试完成！");
    console.log("\n📊 测试结果总结:");
    console.log("  ✅ 初始化连接");
    console.log("  ✅ 工具列表获取");
    console.log("  ✅ 文件写入");
    console.log("  ✅ 文件读取");
    console.log("  ✅ Shell 命令执行");
    console.log("  ✅ 代码搜索");
    console.log("\n🦞 AICodeClaw MCP Server 运行正常！");
    
    process.exit(0);
  }
}

// 启动测试
runTests().catch(error => {
  console.error("❌ 测试失败:", error);
  process.exit(1);
});
